# Generated by Django 4.2.11 on 2026-05-12 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('payment', 'Paiement mission'), ('commission', 'Commission plateforme'), ('pack', 'Achat pack'), ('training', 'Achat formation'), ('refund', 'Remboursement'), ('withdrawal', 'Retrait')], max_length=20)),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('cash', 'Espèces'), ('internal', 'Portefeuille BaaraLink')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('gross_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('commission_amount', models.PositiveIntegerField(default=0)),
                ('net_amount', models.PositiveIntegerField(default=0)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('payee_phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='jobs.job')),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payer', 'status'], name='payments_tr_payer_i_9fe630_idx'), models.Index(fields=['job', 'status'], name='payments_tr_job_id_ff304f_idx'), models.Index(fields=['provider_reference'], name='payments_tr_provide_9bbfff_idx')],
            },
        ),
    ]
