# Generated by Django 4.2.11 on 2026-05-12 12:46

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +22370000000', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Inscription'), ('login', 'Connexion'), ('reset_pin', 'Réinitialisation PIN'), ('verify_change', 'Vérification changement')], default='login', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Vérification OTP',
                'indexes': [models.Index(fields=['phone_number', 'is_used'], name='users_otpve_phone_n_15e101_idx'), models.Index(fields=['expires_at'], name='users_otpve_expires_4f8a2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Format : +22370000000', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='Nom')),
                ('role', models.CharField(choices=[('client', 'Client'), ('provider', 'Prestataire'), ('admin', 'Administrateur')], default='client', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='fr', max_length=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'indexes': [models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'), models.Index(fields=['role'], name='users_user_role_36d76d_idx'), models.Index(fields=['is_active', 'phone_verified'], name='users_user_is_acti_db9d3e_idx')],
            },
        ),
    ]
